server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.231.202:3306/aoyou_fast
    username: root
    password: abc666
  # redis配置
  data:
    redis:
      host: 192.168.231.202
      port: 6379
      password: abc666
      database: 0
      timeout: 10s # 连接超时时间
      lettuce:
        pool:
          min-idle: 0 # 连接池中的最小空闲连接
          max-idle: 8 # 连接池中的最大空闲连接
          max-active: 8 # 连接池的最大数据库连接数
          max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）